services:
#    sopinet_upload_files.example:
#        class: Sopinet\UploadFilesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
   sopinet_upload.form.type.dropzone_type:
        class: Sopinet\UploadFilesBundle\Form\Type\DropzoneType
        arguments: ["@oneup_uploader.templating.uploader_helper", "@doctrine.orm.entity_manager" ,"@oneup_uploader.orphanage_manager"]
        tags:
            - { name: form.type, alias: dropzone_file_gallery }
   sopinet_upload.twig.uploader_extension:
        class: Sopinet\UploadFilesBundle\Twig\Extension\UploaderExtension
        arguments: ['@oneup_uploader.orphanage_manager','@session', '%oneup_uploader.orphanage%']
        tags:
            - { name: twig.extension }

   sopinet_upload.file_namer:
        class: Sopinet\UploadFilesBundle\Service\FileNamer